spring:
  application:
    name: patient-appointment-system
  datasource:
    url: jdbc:mysql://localhost:3306/patient_application
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: admin
      password: admin123
server:
  port: 8080
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com:
      example: DEBUG

springdoc:
  api-docs:
    path: /api-docs
